[workspace]
resolver = "3"
members = ["ghoti-*"]
default-members = ["ghoti-shell"]

[workspace.package]
edition = "2024"
license = "GPL-2.0-only"
repository = "https://github.com/oxalica/ghoti-shell"
description = "POC"
